### ISSUE TITLE
Add info about using logs

### ISSUE THREAD

**Issue by antonmedv** [deployphp/docs#93]

**Comment by TheCelavi** [comment]
I have found out that you can set the path to a file where you want to save log output, example

    set('log_file', __DIR__.'/var/logs/deployer.log'); 

There are some other settings regarding logger, like log_handler and logger (class \Deployer\Deployer)

I have found out that Monolog is not used, some kind of custom logger implementation is used, so PSR-3 standard is not implemented at all.

That is kinda really bad, because it would be awesome to have multiple logging handler, example, FileHandler for everything, SwiftHandler for level ERROR and above.

**Comment by antonmedv** [comment]
Okay, feel free to implement PSR-3 (but try to keep it lightweight, don't require monolog) in PR.
